### ISSUE TITLE
Error: Unable to copy directory entirely

### ISSUE THREAD

**Issue by fresheneesz** [davglass/cpr#20]
Using cpr v1.0.0, I get the error `Unable to copy directory entirely` when i try to use CPR to copy directories in a linux centos environment. Things were working fine when I was using 0.4.2, so I'm just going to switch back to that.

**Comment by davglass** [comment]
Can I get any more information on this? There have only been two commits since that version: 2cd5e30a9d3341a70074bc6d996d8e8d527fdf5b & 3adcb911846c85257ae846037507b786d801fc82

The callback with that error should contain the list of files that had issues. Can you attach that for me? I can't fix what I can't replicate :)

**Comment by fresheneesz** [comment]
Ah, when looking at `error.list` it lead me to realize that cpr no longer overwrites automatically - it was giving me "exists" errors for all my file destinations. Works once I use the overwrite option. Thanks.

**Comment by CharliePops** [comment]
Unfortunately I am using a npm script and the cli doesn't accept options. It would be good to have that feature.

**Comment by trusktr** [comment]
I had the same problem. Adding the `--overwrite` option with the cli fixed the error for me.

The error is not helpful. Might be nice if it says something like "Error: not overwriting files without the 'overwrite' option" or similar.
