### ISSUE TITLE
Copy only changed files

### ISSUE THREAD

**Issue by slavafomin** [davglass/cpr#22]
Hello!

I have a project with extremely big directories. It would be a tremendous improvement if **cpr** would be able to compare files from source and target directory using timestamp and/or filesize.

Thanks!

**Comment by stefanpenner** [comment]
I am unsure if that is something CPR itself should provide, it really is a different beast. 

Although undocumented (although tested), I have a module that supports this: https://github.com/stefanpenner/tree-sync and I use it in cases, where I must maintain some potentially large output dir, instead of just a one-time copy (for which I still use CPR)
